/**
 * MCP Server Configuration
 *
 * Auto-discovers MCP servers from environment variables
 * Supports dynamic server registration and health checks
 */

export interface MCPServerConfig {
  name: string
  endpoint: string
  apiKey?: string
  enabled: boolean
  type: 'http' | 'sse'
  capabilities?: string[]
  metadata?: Record<string, unknown>
}

export interface MCPRegistryConfig {
  servers: Map<string, MCPServerConfig>
  autoDiscovery: boolean
  healthCheckInterval?: number
}

/**
 * Parse environment variables to discover MCP servers
 *
 * Supports patterns:
 * - MCP_SLACK_ENDPOINT=https://api.slack.com/mcp
 * - MCP_SLACK_API_KEY=xoxb-...
 * - MCP_DISCORD_ENDPOINT=https://discord.com/api/mcp
 * - MCP_GITHUB_ENDPOINT=https://api.github.com/mcp
 *
 * General pattern: MCP_{SERVER_NAME}_{PROPERTY}
 */
export function discoverMCPServers(): Map<string, MCPServerConfig> {
  const servers = new Map<string, MCPServerConfig>()
  const mcpEnvVars = Object.keys(process.env).filter(key => key.startsWith('MCP_'))

  // Group env vars by server name
  const serverGroups = new Map<string, Record<string, string>>()

  for (const key of mcpEnvVars) {
    const parts = key.split('_')
    if (parts.length < 3) continue // Need at least MCP_SERVERNAME_PROPERTY

    const serverName = parts[1].toLowerCase()
    const property = parts.slice(2).join('_').toLowerCase()
    const value = process.env[key]

    if (!value) continue

    if (!serverGroups.has(serverName)) {
      serverGroups.set(serverName, {})
    }

    serverGroups.get(serverName)![property] = value
  }

  // Create server configs
  for (const [serverName, properties] of serverGroups) {
    const endpoint = properties.endpoint
    if (!endpoint) {
      console.warn(`[MCP] Server ${serverName} has no endpoint defined, skipping`)
      continue
    }

    const config: MCPServerConfig = {
      name: serverName,
      endpoint,
      apiKey: properties.api_key || properties.apikey || properties.key,
      enabled: properties.enabled !== 'false', // Default to true
      type: (properties.type as 'http' | 'sse') || 'http',
      capabilities: properties.capabilities?.split(',').map(c => c.trim()),
      metadata: {},
    }

    // Add any extra properties to metadata
    for (const [key, value] of Object.entries(properties)) {
      if (!['endpoint', 'api_key', 'apikey', 'key', 'enabled', 'type', 'capabilities'].includes(key)) {
        config.metadata![key] = value
      }
    }

    servers.set(serverName, config)
    console.log(`[MCP] Discovered server: ${serverName} at ${endpoint}`)
  }

  return servers
}

/**
 * Get well-known MCP server patterns
 * Returns suggested configurations for popular platforms
 */
export function getWellKnownServers(): Record<string, Partial<MCPServerConfig>> {
  return {
    slack: {
      type: 'http',
      capabilities: ['messaging', 'channels', 'users'],
      metadata: { platform: 'slack' }
    },
    discord: {
      type: 'http',
      capabilities: ['messaging', 'channels', 'guilds'],
      metadata: { platform: 'discord' }
    },
    twitter: {
      type: 'http',
      capabilities: ['posting', 'reading', 'users'],
      metadata: { platform: 'twitter' }
    },
    github: {
      type: 'http',
      capabilities: ['repositories', 'issues', 'pull_requests'],
      metadata: { platform: 'github' }
    },
    notion: {
      type: 'http',
      capabilities: ['pages', 'databases', 'blocks'],
      metadata: { platform: 'notion' }
    },
    linear: {
      type: 'http',
      capabilities: ['issues', 'projects', 'teams'],
      metadata: { platform: 'linear' }
    },
  }
}

/**
 * Auto-generate MCP server config for a platform
 * Suggests configuration based on common patterns
 */
export function suggestServerConfig(platform: string): Partial<MCPServerConfig> | null {
  const wellKnown = getWellKnownServers()
  const platformLower = platform.toLowerCase()

  if (wellKnown[platformLower]) {
    return {
      name: platformLower,
      enabled: true,
      ...wellKnown[platformLower]
    }
  }

  // Generic config for unknown platforms
  return {
    name: platformLower,
    enabled: true,
    type: 'http',
    capabilities: [],
    metadata: { platform: platformLower, autoGenerated: true }
  }
}

/**
 * Detect which MCP servers are needed based on user request
 * Uses keyword matching to suggest relevant platforms
 */
export function detectRequiredServers(input: string): string[] {
  const inputLower = input.toLowerCase()
  const detectedServers: string[] = []

  const platformKeywords = {
    slack: ['slack', 'channel', 'dm', 'workspace'],
    discord: ['discord', 'server', 'guild', 'voice channel'],
    twitter: ['twitter', 'tweet', 'x.com', 'retweet'],
    github: ['github', 'repository', 'pull request', 'issue', 'commit'],
    notion: ['notion', 'page', 'database', 'workspace'],
    linear: ['linear', 'issue', 'project', 'team'],
  }

  for (const [platform, keywords] of Object.entries(platformKeywords)) {
    if (keywords.some(keyword => inputLower.includes(keyword))) {
      detectedServers.push(platform)
    }
  }

  return detectedServers
}

/**
 * Generate environment variable template for a server
 */
export function generateEnvTemplate(serverName: string): string {
  const upper = serverName.toUpperCase()
  return `# ${serverName.charAt(0).toUpperCase() + serverName.slice(1)} MCP Server
MCP_${upper}_ENDPOINT=https://api.${serverName}.com/mcp
MCP_${upper}_API_KEY=your-api-key-here
MCP_${upper}_ENABLED=true
MCP_${upper}_TYPE=http`
}
