/**
 * Download utilities for agent output
 * Provides functions to download agent responses as Markdown and PDF
 */

/**
 * Download agent response as Markdown file
 * @param content - The markdown content to download
 * @param agentName - Name of the agent that generated the response
 * @param timestamp - Timestamp of the response
 */
export function downloadMarkdown(content: string, agentName: string, timestamp: Date): void {
  // Format timestamp for filename
  const dateStr = timestamp.toISOString().replace(/[:.]/g, '-').slice(0, -5)
  const filename = `agent-response-${dateStr}.md`
  
  // Create markdown file with header
  const header = `---
Generated by: ${agentName}
Date: ${timestamp.toLocaleString()}
---

`
  
  const fullContent = header + content
  
  // Create blob and download
  const blob = new Blob([fullContent], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Download agent response as PDF file
 * @param elementId - ID of the HTML element containing the rendered markdown
 * @param agentName - Name of the agent that generated the response
 * @param timestamp - Timestamp of the response
 * @param content - The markdown content (for fallback)
 */
export async function downloadPDF(
  elementId: string,
  agentName: string,
  timestamp: Date,
  content: string
): Promise<void> {
  try {
    // Dynamic import to avoid SSR issues
    const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
      import('jspdf'),
      import('html2canvas')
    ])
    
    let element = document.getElementById(elementId)
    
    // If element not found, try to use existing rendered markdown
    if (!element) {
      // Look for any element with the message content
      const messageElements = document.querySelectorAll('[id^="message-"]')
      if (messageElements.length > 0) {
        element = messageElements[messageElements.length - 1] as HTMLElement
      }
    }
    
    if (!element) {
      throw new Error(`Element with ID "${elementId}" not found. Please ensure the message is rendered.`)
    }
    
    // Convert HTML to canvas
    const canvas = await html2canvas(element, {
      backgroundColor: '#000000',
      scale: 2, // Higher quality
      logging: false,
      useCORS: true,
      allowTaint: true,
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight,
    })
    
    const imgData = canvas.toDataURL('image/png', 1.0)
    
    // Calculate PDF dimensions
    const imgWidth = canvas.width
    const imgHeight = canvas.height
    const pdfWidth = 210 // A4 width in mm
    const pdfHeight = (imgHeight * pdfWidth) / imgWidth
    const pageHeight = 297 // A4 height in mm
    
    // Create PDF
    const pdf = new jsPDF('p', 'mm', 'a4')
    
    // Check if content fits on one page
    if (pdfHeight <= pageHeight) {
      // Single page - add image
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
    } else {
      // Multiple pages needed
      let heightLeft = pdfHeight
      let position = 0
      
      // Add first page
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight)
      heightLeft -= pageHeight
      
      // Add additional pages if content is longer than one page
      while (heightLeft > 0) {
        position = heightLeft - pdfHeight
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight)
        heightLeft -= pageHeight
      }
    }
    
    // Add metadata
    pdf.setProperties({
      title: `Agent Response - ${agentName}`,
      subject: 'Agent Response',
      author: agentName,
      creator: 'ZwartifyOS',
    })
    
    // Format timestamp for filename
    const dateStr = timestamp.toISOString().replace(/[:.]/g, '-').slice(0, -5)
    const filename = `agent-response-${dateStr}.pdf`
    
    // Download PDF
    pdf.save(filename)
  } catch (error) {
    console.error('Error generating PDF:', error)
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred'
    throw new Error(`Failed to generate PDF: ${errorMessage}`)
  }
}

